name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Go build
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.3'
      - run: go build github.com/movetokube/postgres-operator/cmd/manager